### ISSUE TITLE
Request for collaboration

### ISSUE THREAD

**Issue by SkepticMystic** [Robin-Haupt-1/Obsidian-Map-of-Content#18]
Hey Robin :)

Interesting plugin you've made here, I only just came across it today!
I'm not sure if you've heard of [Breadcrumbs](https://github.com/SkepticMystic/breadcrumbs) before, it is a plugin I've been working on for some time now.
My understanding is that both plugins do pretty similar stuff! I don't have any issue with this (monopolies are counter to innovation 😋), but perhaps collaborating our efforts would be more useful? Let me know what you think. Breadcrumbs is quite well established, perhaps I can show you around the codebase and we can work together.

Kind Regards
SkepticMystic

**Comment by claremacrae** [comment]
Please pardon the intrusion...

As a new Obsidian user, I've been looking for a breadcrumbs mechanism that works on directory structure, without needing manual tagging (on the thousands of notes I've imported from my previous system). I think this is what the existing Breadcrumbs plugin requires.

I just wanted to say that I feel like there are several valid independent bread-crumbs use-cases/strategies:

- Show me where I am, and the levels above me in the folder-structure to help me navigate up the branches to the top-level
- Show me my history of the links I followed to get here (like some DokuWiki setups)
- Show me, based on hand-maintained data, like parent/child tags

**Comment by SkepticMystic** [comment]
@claremacrae thanks for the input, I totally agree. There are many different ways to go with this. I think the question, then, is should these features be put into one plugin, or spread over multiple? I think there are pros and cons to both. 
Separate plugins means less clutter, less unnecessary stuff for those who don't use every feature. 
One plugin means there is lots of room for integration between different features. 

There are some things which this plugin does which Breadcrumbs doesn't. However, I have some feature requests for breadcrumbs to work on the existing directory structure, or even to use nested tags. So I do intend to implement those features at some point.
I don't think there is a right answer to this, but it would be great to hear what Robin thinks.
Personally, I would love if we could integrate the two. Use Breadcrumbs' existing infrastructure, and add extra stuff which Obsidian-MOC does already.

**Comment by Robin-Haupt-1** [comment]
Hi @SkepticMystic ,

i agree that consolidating similar plugins sounds like a great idea. I hadn't known about Breadcrumbs before, i'm trying it out right now.

**Comment by Robin-Haupt-1** [comment]
In terms of the question of features vs. clutter, we could try for a seemless integration between the relatively effortless automatic treebuilding i have and modifying that with specifiers like in Breadcrumbs when needed. 

I would want the resulting plugin to stay as simple and straightforward to use as possible, ideally to the point where it feels like a native feature, because i want it to reach as many people as could benefit from it, which as i see it is most Obsidian users. 

The point should be to automatically derive information from the vault without having to put in too much work. 
The way i see it, there's an inverse relationship between needing an overview of your vault and being able to create one by tagging each note manually. In other words: the bigger the vault and the more complex the relationship's between the notes, the more work it is to specify the relationships between all notes by hand. 

My focus for the future of my addon would be on: 

- integrating with the native tagging and folder system to get as much information from that as possible
- working on the views and improving them to where they can replace the native Backlinks view by also displaying the backlinks that don't feature in any MOC graphs
- making the plugin respond to user behaviour by analyzing and displaying the most used (and thus most relevant) paths and notes first
- highlighting notes that need attention because they're not well linked or related to any still relevant notes to avoid "note rot" where notes fade into obscurity while bloating up your vault (regularly combing through your old notes to keep them in order and well integrated with newer ones is also a great way to remember what you wrote about, as it combines spaced repetition with the task of linking old thoughts with new ones (elaboration) which also aids memory tremendously)
- the ability to maintain distinct hierarchies centered around different central notes, so as to in effect have virtual vaults within the same vault

Features that Breadcrumbs already has and that i would want are:

- allowing for fine-tuning of paths with minimalistic custom references in the notes to augment the algorithm where necessary 
- creating nice visualizations
- having many options for fine-tuning, integrations and exports
- having different hierarchies


I believe that it would be a better idea to build all this on top of my codebase, which is still comparatively small and which i've worked hard to make as orderly and intuitive to work with as possible. But we still could definitely collaborate on that, after all our visions are very similar, and any help (from anybody) would be most welcome. You could help me implement the features you wrote before, and if you like i could help you implement something similar to my pathfinding in Breadcrumbs, if you want to continue developing that.

Could you lay out what you would image the merged plugin to look like?

**Comment by Robin-Haupt-1** [comment]
@SkepticMystic, could you give a short update on your thoughts?
