### ISSUE TITLE
Would you be open to consider a different name for your plugin?

### ISSUE THREAD

**Issue by nickmilo** [Robin-Haupt-1/Obsidian-Map-of-Content#19]
I hope it is okay to share this here... I'm excited to try out your plugin. It looks really cool; no matter where you are, you can find your way back home. 🙌

Can I ask you to consider a different name for your plugin? I worry it will confuse people about what a Map of Content is. A Map of Content (MOC) is a note that mainly has links to other notes, thus "mapping" the contents of multiple notes in a digital library. 

But your plugin is not an MOC. So I worry it is going to create a lot more confusion for everyone, especially in the forums for people to explain: _"No, there's a Map of Content, which is already hard to describe, but that's different from this Plugin (also called the same name)."_ 

Since your plugin helps you find your way back home, perhaps you could keep the "mapping" spirit, but give it a more descriptive name. Here are some alternatives I hope it's okay to share:

- Home Navigator
- Terrain Mapper
- X Marks the Spot
- It's Over There
- Trails
- Happy Trails
- Directions Home
- Back to home
- No Place Like Home

Anyways, thanks for your time and hopefully your openness to this suggestion; I think the community enjoy your plugin!

**Comment by nickmilo** [comment]
Why I'm inspired by your plugin is because orienting ourselves is more important than we often realize. In the 1985 book Ender's Game, orientation is paramount for success. 

Oh I also thought that "Beacon" might be a good name too

**Comment by Robin-Haupt-1** [comment]
Hi, thanks for your feedback!

I like thinking about names. At first i wanted to call it "Top Level Index" from the idea that everything centered around one index, but that was just a working title. 

I thought about using a more creative, symbolic name like "Map and Compass" since it shows you where you are, where you can go from there and it always points home to "true north" as well. Map and Compass also eerily sounds like Map of Content which is probably why i liked it so much.

Anyway, since the plugin does generate a map of all the note's descendants and also shows the path to the central note i think it does generate a Map of Content in the traditional sense and i think the name is appropriate. I was aware of the usual use of the term and i wanted my plugin to ring a bell, so i chose that name and i don't want to change it, at least not in the foreseeable future. I want to focus on getting it published and working on the main functionality first. 

I'm not sure i've done a good enough job of demonstrating what the plugin can do yet. Maybe this is a better example of the Map of Content it can create than the stubby little tree in the readme (This is from my personal vault): [link](https://raw.githubusercontent.com/Robin-Haupt-1/Obsidian-Map-of-Content/main/doc/example%203.png)
As you can see, it is a great replacement for a handmade MOC without all the work (and instantly updated once you change anything)

Im happy that you'd like to try the plugin. You can do so already, without having to wait for it to be added to the official list which could take a few weeks. Open the folder where your vault is stored and create a new folder called whatever you like in your_vault/.obsidian/plugins/new_folder. Then download main.js and manifest.json from [here](https://github.com/Robin-Haupt-1/Obsidian-Map-of-Content/releases/tag/0.1.0) and copy them into that new folder. Restart Obsidian and it will show up.

**Comment by nickmilo** [comment]
Thanks for your reply and instructions on how to test it out. This is pretty great. Here's a cool result:

<img width="345" alt="map of connections home" src="https://user-images.githubusercontent.com/35411533/135732188-5c3bcfc6-2c36-4e4a-bffa-4f635f2e8485.png">

It reminds me of James Burke's wonderful BBC series from 1978 called "Connections". He would track some small obscure thing to the development of the nuclear bomb. Map and Compass is a nice alternative, but I understand you are partial to Map of Content. You know..."Map of Connections" sounds pretty stellar actually. Similar enough to invoke Maps of Content, but strong enough to stand on its own—and it pays subtle tribute to Burke's truly amazing work on "Connections" (here's [episode one](https://www.youtube.com/watch?v=XetplHcM7aQ)). Anyways, food for thought...

Side question: What are the `...` indicating in the tree?

**Comment by Robin-Haupt-1** [comment]
The `...` indicate that there are children that are hidden because they are more than 3 levels removed.

I hope you'll enjoy using the plugin. If it's alright with you then i'll close this issue soon.
